-- =====================================================
-- Booking Service - Seed bookings data
-- Version: V2
-- =====================================================

INSERT INTO bookings (user_id, car_id, start_date, end_date, status, total_price, cancel_deadline) VALUES
    -- CREATED (1)
    (5, 3, CURRENT_TIMESTAMP + INTERVAL '7 days', CURRENT_TIMESTAMP + INTERVAL '9 days', 'CREATED', 100.00, (CURRENT_TIMESTAMP + INTERVAL '7 days') - INTERVAL '2 day'),

    -- PENDING (2)
    (6, 7, CURRENT_TIMESTAMP + INTERVAL '3 days', CURRENT_TIMESTAMP + INTERVAL '8 days', 'PENDING', 450.00, (CURRENT_TIMESTAMP + INTERVAL '3 days') - INTERVAL '2 day'),
    (7, 9, CURRENT_TIMESTAMP + INTERVAL '5 days', CURRENT_TIMESTAMP + INTERVAL '7 days', 'PENDING', 300.00, (CURRENT_TIMESTAMP + INTERVAL '5 days') - INTERVAL '2 day'),

    -- CONFIRMED (3)
    (4, 2, CURRENT_TIMESTAMP + INTERVAL '1 day', CURRENT_TIMESTAMP + INTERVAL '8 days', 'CONFIRMED', 196.00, (CURRENT_TIMESTAMP + INTERVAL '1 day') - INTERVAL '2 day'),
    (5, 4, CURRENT_TIMESTAMP + INTERVAL '2 days', CURRENT_TIMESTAMP + INTERVAL '6 days', 'CONFIRMED', 220.00, (CURRENT_TIMESTAMP + INTERVAL '2 days') - INTERVAL '2 day'),
    (6, 11, CURRENT_TIMESTAMP + INTERVAL '15 days', CURRENT_TIMESTAMP + INTERVAL '18 days', 'CONFIRMED', 420.00, (CURRENT_TIMESTAMP + INTERVAL '15 days') - INTERVAL '2 day'),

    -- COMPLETED (3)
    (4, 5, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '25 days', 'COMPLETED', 240.00, (CURRENT_TIMESTAMP - INTERVAL '30 days') - INTERVAL '2 day'),
    (5, 8, CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '17 days', 'COMPLETED', 300.00, (CURRENT_TIMESTAMP - INTERVAL '20 days') - INTERVAL '2 day'),
    (7, 12, CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '13 days', 'COMPLETED', 360.00, (CURRENT_TIMESTAMP - INTERVAL '15 days') - INTERVAL '2 day'),

    -- CANCELLED (1)
    (6, 6, CURRENT_TIMESTAMP + INTERVAL '20 days', CURRENT_TIMESTAMP + INTERVAL '24 days', 'CANCELLED', 380.00, (CURRENT_TIMESTAMP + INTERVAL '20 days') - INTERVAL '1 day');
