DROP TABLE IF EXISTS car_images;
DROP TABLE IF EXISTS cars;
DROP TYPE IF EXISTS car_status;
DROP TYPE IF EXISTS car_class;

CREATE TYPE car_status AS ENUM ('AVAILABLE', 'RENTED', 'MAINTENANCE', 'UNCONFIRMED', 'CANCELED');
CREATE TYPE car_class  AS ENUM ('ECONOMY', 'COMFORT', 'BUSINESS', 'LUXURY');

CREATE TABLE cars (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand        VARCHAR(50)  NOT NULL,
    model        VARCHAR(50)  NOT NULL,
    year         INTEGER      NOT NULL CHECK (year >= 1950),
    car_class    car_class    NOT NULL,
    price_per_day REAL        NOT NULL CHECK (price_per_day > 0),
    user_id      BIGINT       NOT NULL,
    status       car_status   NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP
);

CREATE TABLE car_images (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id       BIGINT        NOT NULL,
    image_data   VARBINARY(10485760) NOT NULL,
    content_type VARCHAR(100)  NOT NULL,
    file_name    VARCHAR(255)  NOT NULL,
    file_size    BIGINT        NOT NULL,
    is_main      BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_car_images_car_id FOREIGN KEY (car_id) REFERENCES cars(id) ON DELETE CASCADE
);
